apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    ports:
        -   port: 3306
    selector:
        app: mysql
    clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    selector:
        matchLabels:
            app: mysql
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                -   image: mysql:latest
                    name: mysql
                    env:
                        -   name: MYSQL_USER
                            valueFrom:
                                secretKeyRef:
                                    key: mysql-user-username
                                    name: mysql-secret
                        -   name: MYSQL_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: mysql-user-password
                                    name: mysql-secret
                        -   name: MYSQL_ROOT_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: mysql-user-password
                                    name: mysql-secret
                    ports:
                        -   containerPort: 3306
                            name: mysql
                    volumeMounts:
                        -   name: mysql-initdb
                            mountPath: /docker-entrypoint-initdb.d

            volumes:
                -   name: mysql-initdb
                    configMap:
                        name: mysql-configmap
